---
- name: gitlab | create directory
  file: path={{ item }} state=directory
  with_items:
    - /data/gitlab/config
    - /data/gitlab/data
    - /data/gitlab/logs


- name: gitlab | create .env
  lineinfile:
    path: /data/gitlab/.env
    regexp: '^COMPOSE_PROJECT_NAME='
    state: present
    create: yes
    line: COMPOSE_PROJECT_NAME=gitlab


- name: gitlab | copy docker-compose.yml
  template:
    src: docker-compose.yml
    dest: /data/gitlab
  notify: restart gitlab


- name: gitlab | Copying gitlab.rb
  template: 
     src: gitlab.rb 
     dest: /data/gitlab/config/gitlab.rb
     mode: 0600
  notify: restart gitlab


- name: gitlab | create ssl-cert dir
  file: path=/data/gitlab/config/ssl-certs state=directory


- name: gitlab | copyng ssl certificates
  copy:
    src: "{{ item }}"
    dest: /data/gitlab/config/ssl-certs/
  with_items:
    - /etc/ansible/files/ssl-certs/enciso.site.crt
    - /etc/ansible/files/ssl-certs/enciso.site.key


- name: start gitlab
  shell: "docker-compose -f docker-compose.yml up -d"
  args:
    chdir: /data/gitlab
