---
## GENERAL
proxy_enabled: false
domain_company: enciso.site

## SELINUX
selinux_enabled: true

## FIREWALL
firewalld_disabled: False
firewalld_rules:
      ssh:
        port: 22
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
      remote-ssh:
        port: 2222
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
      http:
        port: 80
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
      https:
        port: 443
        protocol: tcp
        state: enabled
        zone: public
        permanent: true
