version: '3.1'

services:

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:{{ gitlab_version | default('latest') }}
    volumes:
      - /data/gitlab/config:/etc/gitlab
      - /data/gitlab/data:/var/opt/gitlab
      - /data/gitlab/logs:/var/logs/gitlab
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    restart: always
